### ISSUE TITLE
Autentication with new GuzzleHttp\Client()

### ISSUE THREAD

**Issue by ghost** [SERVEXS/bol-retailer-client#1]
Thank you for this script.
I do run into 1 problem, i cannot seem to login/autenticate
The readme states to use new GuzzleHttp\Client()
I treid different things, can anyone send me in the right direction?

I treid:

use GuzzleHttp\Client;

$apiInstance = new ServeXS\BolRetailer\v7\Api\CommissionsApi(
    // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
    // This is optional, `GuzzleHttp\Client` will be used as default.
    new GuzzleHttp\Client([                                                                                                                                             
    'base_uri' => 'https://login.bol.com/token?grant_type=client_credentials',                                                                                                                                                   
    'headers' => [                                                                                                                                                                   
        'Authorization' => ['user_id','secret_id']
    ],                                                                                                                                                                               
])
);

Of course for the id's I use the orginals.

With regards, Theo

**Comment by jbours** [comment]
Hi Theo,

Please be aware this client is mainly created for our own use cases and is not an officially (supported) client by bol.com.

The client is automatically [generated](https://github.com/OpenAPITools/openapi-generator-cli) based on the openapi/swagger spec for the [v7 ](https://api.bol.com/retailer/public/apispec/Retailer%20API%20-%20v7 )api which Bol provides. Unfortunately the calls for authentication (OAuth2) are not included in the api-spec, and therefore not included in this client. This is the part which you have implement yourself. Below are some examples which may help you further. 

Bol.com videos: https://api.bol.com/retailer/public/Retailer-API/tutorial-videos.html

Authentication process: https://api.bol.com/retailer/public/Retailer-API/authentication.html

example custom client:
```php
<?php 

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\RequestInterface;
use GuzzleHttp\HandlerStack;

$stack= new HandlerStack::create();

 $stack->push(
            Middleware::mapRequest(
                fn(RequestInterface $request) => $request->withHeader(
                    'Content-Type',
                    'application/vnd.retailer.v7+json'
                )
            )
        );

$client = new Client(
[
  
  'headers' => [
    'handler' => $stack,
    'authorization' => 'Bearer <access-token>',
  ],
]
);
```

Example fetch access token:
```php
<?php

$response = (new Client())->post(
            'https://login.bol.com/token?grant_type=client_credentials',
            [
                'exceptions' => true,
                'auth'       => [
                   <your-username>,
                    <your-password>,
                ],
            ]
        );

$data = json_decode($response->getBody()->getContents(), true, 512, JSON_THROW_ON_ERROR);

$accessToken = $data['access_token']; // store this value to use as bearer token.
$expiresIn = $data['expires_in']; // store this value to determine if you need to fetch or refresh the access token.
```

Call with custom client:
```php
$config = new  \ServeXS\BolRetailer\v7\Api\Configuration::getDefaultConfiguration();
$config->setUsername('<username>');
$config->setPassword(`<password>`);

// $client = the custom client
$ordersApi = new \ ServeXS\BolRetailer\v7\Api\OrdersApi($client, $config);

$response = $ordersApi->getOrders();
```
